[package]
name = "nvim_rs"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.5.1", features = [ "neovim-0-10", "mlua" ] }
mlua = { version = "0.10.0", features = [ "luajit", "module" ] }
